-- =========================================================
-- 1. ddl: create meals table
-- =========================================================

create table if not exists meals (
                                     id bigint generated by default as identity primary key,
                                     created_at timestamptz not null default now(),
    title text not null
    );

-- =========================================================
-- 2. ddl: extend meal_plans
-- =========================================================

alter table meal_plans
    add column if not exists meal_id bigint;

-- =========================================================
-- 3. data migration
-- =========================================================

insert into meals (title)
select distinct meal_title
from meal_plans
where meal_title is not null
  and meal_title not in (
    select title from meals
);

update meal_plans mp
set meal_id = m.id
    from meals m
where mp.meal_title = m.title;

-- =========================================================
-- 4. constraints
-- =========================================================

alter table meal_plans
    add constraint meal_plans_meal_id_fkey
        foreign key (meal_id)
            references meals (id)
            on delete restrict;

alter table meal_plans
    alter column meal_id set not null;

alter table meal_plans
drop column meal_title;

-- =========================================================
-- 5. row level security
-- =========================================================

alter table meals enable row level security;

create policy "enable crud for authenticated users only"
on meals
for all
to authenticated
using (true)
with check (true);

-- =========================================================
-- 6. grants
-- =========================================================

grant all on table meals to anon;
grant all on table meals to authenticated;
grant all on table meals to service_role;

grant all on sequence meals_id_seq to anon;
grant all on sequence meals_id_seq to authenticated;
grant all on sequence meals_id_seq to service_role;
